apiVersion: v1
kind: Secret
metadata:
  name: sampleapisecrets
type: Opaque
stringData:
  appsettings.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*" ,
      "TestConfig": "{{.Values.namespace}}"
    }
